site_name: Bicep Module Library
theme:
  name: material
  palette: 
    primary: black
    accent: blue
    # # Palette toggle for light mode
    # - scheme: default
    #   toggle:
    #     icon: material/brightness-7 
    #     name: Switch to dark mode

    # # Palette toggle for dark mode
    # - scheme: slate
    #   toggle:
    #     icon: material/brightness-4
    #     name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - search.suggest
    - navigation.footer
    - content.code.copy

nav:
  - HOME: index.md
  - Pattern modules:
    - Storage Azure Files: ptn-storageAzureFiles.md
  - Resource modules:
    - Key Vault: 
      - Main: res-keyVault.md
      - Secrets: keyVault-secrets.md
      - Keys: keyVault-keys-md
      - Access Policy: keyVault-access-policy.md
    - Network:
        - Application Security Groups: network-applicationSecurityGroups.md
        - Network Interfaces: network-networkInterfaces.md
        - Network Security Groups: 
            - Main: network-networkSecurityGroups.md
            - Security Rules: networkSecurityGroups-securityRules.md
        - Private Endpoints: 
            - Main: network-privateEndpoints.md
            - Private DNS Zone Groups: privateEndpoints-privateDnsZoneGroups.md
        - Public IP Addresses: network-publicIPAddresses.md
        - Route Tables: network-routeTables.md
        - Virtual Networks:
            - Main: network-virtualNetworks.md
            - Virtual Network Peerings: virtualNetworks-virtualNetworkPeerings.md
            - Subnets: virtualNetworks-subnets.md


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences


extra_css:
  - stylesheets/extra.css

extra:
  generator: true
  


plugins:
  - search
