name: 'Lint and PSRule Analysis'
description: 'Performs linting and PSRule analysis'
inputs:
  moduleFilePath:
    description: 'Path to the module file'
    required: true
  testFilePath:
    description: 'Path to the test file directory'
    required: false
  azureCredentials:
    description: 'Azure credentials in JSON format'
    required: true

runs:
  using: 'composite'
  steps:
    - run: |
        az bicep build --file ${{ inputs.moduleFilePath }}
      shell: bash
    # Check for "tests" folder
    - name: Check for "tests" folder using PowerShell
      run: |
        $moduleFilePath = "${{ env.MODULE_FILE_PATH }}"
        $moduleDirPath = [System.IO.Path]::GetDirectoryName($moduleFilePath)
        $testsFilePath = Join-Path $moduleDirPath -ChildPath "tests"
        $exists = Test-Path $testsFilePath
        echo "testsExist=$exists" >> $GITHUB_ENV
      shell: pwsh

    - name: Run PSRule analysis
      if: env.testsExist == 'true'
      uses: microsoft/ps-rule@v2.9.0 
      with:
        modules: PSRule.Rules.Azure # (2)
        inputPath: ${{ env.MODULE_FILE_PATH }}