name: 'Lint and PSRule Analysis'
description: 'Performs linting and PSRule analysis'
inputs:
  moduleFilePath:
    description: 'Path to the module file'
    required: true
  testFilePath:
    description: 'Path to the test file directory'
    required: false
  azureCredentials:
    description: 'Azure credentials in JSON format'
    required: true

runs:
  using: 'composite'
  steps:
    - run: |
        az bicep build --file ${{ inputs.moduleFilePath }}
      shell: bash
    # Check for "tests" folder
    - name: Check for "tests" folder using PowerShell
      run: |
        $moduleFilePath = "${{ env.MODULE_FILE_PATH }}"
        $moduleDirPath = [System.IO.Path]::GetDirectoryName($moduleFilePath)
        $testsFilePath = Join-Path $moduleDirPath "tests"
        $exists = Test-Path $testsFilePath
        echo "testsExist=$exists" >> $GITHUB_ENV
      shell: pwsh

    
    # Install PSRule.Rules.Azure
    - name: Install PSRule.Rules.Azure
      if: env.testsExist == 'true'
      run: |
        pwsh -Command "Install-Module -Name PSRule.Rules.Azure -Scope CurrentUser -Force"
      shell: pwsh
    
    # Analyze Azure template files with PSRule
    - name: Analyze Azure template files
      if: env.testsExist == 'true'
      run: |
        pwsh -Command "Invoke-PSRule -Module PSRule.Rules.Azure -InputPath '${{ env.TEST_FILE_PATH }}'"
      shell: pwsh
