name: Deploy Environment - TEMPLATE_PLACEHOLDER

on: workflow_dispatch
#   push:
#     branches:
#     - main
#     paths:
#     - "deploy/environment/deploy.bicepparam"

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  LOCATION: 'westeurope'
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  DEPLOYMENT_NAME: 'Deploy-environment-${{ github.run_number }}'
  STORAGE_BICEP_FILE: './environment/deploystorage.bicep'
  STORAGE_BICEP_FILE_PARAM: './environment/deploystorage.bicepparam'

jobs:
  deployAndUpload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: azure/login@v2.1.1
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
      - name: Install Bicep CLI
        run: |
          az bicep install
    
      - name: Verify Bicep Installation
        run: |
          az bicep version

      - uses: Azure/cli@v2.0.0
        with:
          inlineScript: |
            echo "Linting Bicep file"
            az bicep build --file ${{ env.STORAGE_BICEP_FILE }}
        env:
          AZURE_CORE_COLLECT_TELEMETRY: 'no'
      - name: Deploy Prerequisite Resources
        id: deploy
        uses: azure/arm-deploy@v2
        with:
          scope: subscription
          region: ${{ env.LOCATION }}
          subscriptionId: ${{ env.ARM_SUBSCRIPTION_ID }}
          template: './environment/deploystorage.bicep'
          parameters: 'deploymentEnvironment=dev avdWorkloadSubsId=9d4dc425-441e-4724-9154-6ea08c34f756 avdSessionHostLocation=westeurope'
          failOnStdErr: false  
      - name: Upload files to Storage Account
        run: |
          for file in $(ls modules/scripts/*); do
            az storage blob upload --account-name ${{ steps.deploy.outputs.storageAccountName }} --container-name ${{ steps.deploy.outputs.containerName }} --file "$file" --name "$(basename $file)"
          done
